export const SET_REVIEW_ID = 'SET_REVIEW_ID'

export const SET_SEARCH_LIST = 'SET_SEARCH_LIST'

export const SET_FILMMAKER_COLLECT = 'SET_FILMMAKER_COLLECT'

export const SET_WANT_TO_SEE = 'SET_WANT_TO_SEE'

export const SET_SEEN = 'SET_SEEN'
